{panaedra/msi/logic/ctop_interface.i} 

interface paninui.view.interfaces.i_showlocationtype_groupframe_right:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_showlocationtype_groupframe_right.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-12-11 03:30:58+01:00 $ 
    Date Modified: $Modtime: 2009-12-11 03:30:00+01:00 $ 

      Description: OVID# interface

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/


end interface.

/* EOF */ 
