{panaedra/msi/logic/ctop_interface.i} 

interface paninui.view.interfaces.i_uiframe_tty:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_uiframe_tty.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2010-01-04 11:35:43+01:00 $ 
    Date Modified: $Modtime: 2010-01-04 11:35:19+01:00 $ 

      Description: paninui.dll i_uiframe stub for tty/unix

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/


end interface.

/* EOF */ 
