{panaedra/msi/logic/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_groupframe:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_groupframe.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-09-02 16:45:46+02:00 $ 
    Date Modified: $Modtime: 2009-09-02 16:45:39+02:00 $ 

      Description: UI elements that can group a collection of UI widgets, and 
                   move the focus to that group, and disable/enable that group.
                   I.E. Forms Groupbox of WPF StackPanel.

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  
end interface.

/* EOF */
