{panaedra/msi/logic/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_grid:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_grid.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-08-29 23:05:42+02:00 $ 
    Date Modified: $Modtime: 2009-08-29 23:05:03+02:00 $ 

      Description: Grid, and everything that can be considered as a one-dimensional(*) grid : 
                   grid, listbox, progress browse, OLE Excel e.a..
                   The interface is realization independent: WPF DataGrid, 
                   Forms DataViewGrid, Unix CHUI browse, all are widgettype_grid. 
                   
                   (*) for multi-dimensional grids, use i_widgettype_tree.

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
