{panaedra/msi/logic/ctop_interface.i}
interface paninui.view.interfaces.i_widgetproperty_selecteditems:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgetproperty_selecteditems.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-09-02 16:45:47+02:00 $ 
    Date Modified: $Modtime: 2009-09-02 16:45:39+02:00 $ 

      Description: add_your_comments_here

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  
end interface.

/* EOF */
