{panaedra/msroot/msutil/logic/top_i/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_button:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_button.cls $ 
          Version: $Revision: 2 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2010-01-27 21:10:16+01:00 $ 
    Date Modified: $Modtime: 2010-01-27 19:30:12+01:00 $ 

      Description: Button, and everything that can be considered as a button : 
                   menu-item, clickable-image, checkbox/togglebox, url-link,
                   e.a..
                   The interface is realization independent: WPF Button, 
                   Forms Button, Unix CHUI Button, all are widgettype_button. 

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
