{panaedra/msi/logic/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_combobox:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_combobox.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-08-29 23:05:42+02:00 $ 
    Date Modified: $Modtime: 2009-08-29 23:05:03+02:00 $ 

      Description: Combo-box, and everything that can be considered as a combo-box, 
                   even with much less functionality (which will be silently ignored 
                   if used at runtime): 
                   texbox, editor, label, statusbar, windows titlebar, 
                   e.a.
                   The interface is realization independent: WPF RichText, 
                   Forms TextBox, Unix CHUI combo-box, all are widgettype_combobox. 

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
