{panaedra/msroot/msutil/logic/top_i/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_tree:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_tree.cls $ 
          Version: $Revision: 2 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2010-01-27 21:10:16+01:00 $ 
    Date Modified: $Modtime: 2010-01-27 19:30:13+01:00 $ 

      Description: Treeview, and everything that can be considered as multi-dimensional 
                   branch-structured display data: 
                   treeview, multidimensional grid, WPF TreePanel structure, window menu, 
                   context menu, e.a..
                   The interface is realization independent: WPF TreePanel, 
                   Forms TreeView, Unix CHUI browse with custom treelogic, 
                   all are widgettype_grid. 
                   
  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
