{panaedra/msi/logic/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_toolbar:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_toolbar.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-10-20 14:16:56+02:00 $ 
    Date Modified: $Modtime: 2009-10-20 13:55:07+02:00 $ 

      Description: UI elements that have underlying generic elements, which generic name 
                   should be prepended by the custom name of the toolbar.
                   
                   I.e. Generic button ".Cre" on toolbar "toolbarXyZebra" gets logical 
                   name XyZebra.Cre.

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  
end interface.

/* EOF */
