{panaedra/msroot/msutil/logic/top_i/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_datasource:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_datasource.cls $ 
          Version: $Revision: 2 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2010-01-27 21:10:16+01:00 $ 
    Date Modified: $Modtime: 2010-01-27 19:30:11+01:00 $ 

      Description: DataSource widget. 
                   Can be used for linking queries and datasources. 

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
