{panaedra/msi/logic/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_griditem:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_griditem.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-09-02 16:45:46+02:00 $ 
    Date Modified: $Modtime: 2009-09-02 16:45:39+02:00 $ 

      Description: widgettype_griditem are items in a grid. 
                   This interface is (for now) system-only.
                   

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
