{panaedra/msi/logic/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_any:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_any.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-09-02 16:45:46+02:00 $ 
    Date Modified: $Modtime: 2009-09-02 16:45:39+02:00 $ 

      Description: Any widget. 
                   Can be used for generic properties like visible and enabled. 

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
