{panaedra/msroot/msutil/logic/top_i/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_any:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_any.cls $ 
          Version: $Revision: 2 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2010-01-27 21:10:16+01:00 $ 
    Date Modified: $Modtime: 2010-01-27 19:30:12+01:00 $ 

      Description: Any widget. 
                   Can be used for generic properties like visible and enabled. 

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
