{panaedra/msroot/msutil/logic/top_i/ctop_interface.i}
interface paninui.view.interfaces.i_widgetproperty_enabled:  

  /****************************** Source Header ********************************\

      Description: Empty interface

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  
end interface.

/* EOF */
