{panaedra/msi/logic/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_form:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_form.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-10-23 18:11:54+02:00 $ 
    Date Modified: $Modtime: 2009-10-23 18:07:54+02:00 $ 

      Description: Indicates a Windows Form (read: Window). 
      
                   This is always a seperate window (Forms or WPF), 
                   
                   In most cases it will be the MDI Master Window itself. 
                   
  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
