{panaedra/msi/logic/ctop_interface.i}

interface paninui.view.interfaces.i_widgettype_query:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgettype_query.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-10-03 22:37:16+02:00 $ 
    Date Modified: $Modtime: 2009-10-03 22:35:29+02:00 $ 

      Description: Query widget. 
                   Can be used for linking queries and datasources. 

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
