{panaedra/msroot/msutil/logic/top_i/ctop_interface.i} 

interface paninui.view.interfaces.i_widgetmovetype_mdi_left_bottom:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive:  $ 
          Version: $Revision:  $ 
       Programmer: $Author: $ 
     Date Checkin: $Date:  $ 
    Date Modified: $Modtime:  $ 

      Description: 

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/


end interface.

/* EOF */ 
