{panaedra/msi/logic/ctop_interface.i}
interface paninui.view.interfaces.i_widgetproperty_text:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/interfaces/i_widgetproperty_text.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-10-09 12:25:23+02:00 $ 
    Date Modified: $Modtime: 2009-10-09 12:24:16+02:00 $ 

      Description: add_your_comments_here

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  
end interface.

/* EOF */