{panaedra/msroot/msutil/logic/top_i/ctop_interface.i} 


interface panaedra.msroot.msutil.interfaces.i_language_any:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive:  $ 
          Version: $Revision:  $ 
       Programmer: $Author: $ 
     Date Checkin: $Date:  $ 
    Date Modified: $Modtime:  $ 

      Description: any language

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  

end interface.

/* EOF */ 
