{panaedra/msroot/msutil/logic/top_i/ctop_interface.i} 

interface panaedra.msroot.msutil.interfaces.i_messageboxtype_yesnocancel:  

  /****************************** Source Header ********************************\

      Description: Overload ID interface

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/


end interface.

/* EOF */ 
