{panaedra/msi/logic/ctop_interface.i} 

interface panaedra.msroot.msutil.interfaces.i_messageboxtype_debug:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/panaedra/msroot/msutil/interfaces/i_messageboxtype_debug.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-10-22 20:14:40+02:00 $ 
    Date Modified: $Modtime: 2009-10-22 20:12:55+02:00 $ 

      Description: Overload ID interface

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/


end interface.

/* EOF */ 
