{panaedra/msi/logic/ctop_interface.i} 

interface panaedra.msroot.msutil.interfaces.i_modalitydata:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/panaedra/msroot/msutil/interfaces/i_modalitydata.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-12-20 16:25:30+01:00 $ 
    Date Modified: $Modtime: 2009-12-20 14:51:17+01:00 $ 

      Description: Data for the ModalityResponse call.

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  define property cName as character no-undo get.

end interface.

/* EOF */ 
