{panaedra/msi/logic/ctop_interface.i} 

interface panaedra.msroot.msutil.interfaces.i_scopetableclient:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/panaedra/msroot/msutil/interfaces/i_scopetableclient.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2010-01-12 07:27:54+01:00 $ 
    Date Modified: $Modtime: 2010-01-12 01:52:12+01:00 $ 

      Description: An object which wants to ask some data from a ScopeTable object

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/


end interface.

/* EOF */ 
