{panaedra/msroot/msutil/logic/top_i/ctop_interface.i}

interface panaedra.msroot.msutil.interfaces.i_triggerlogic:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/panaedra/msroot/msutil/interfaces/i_triggerlogic.cls $ 
          Version: $Revision: 2 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2010-01-27 21:10:16+01:00 $ 
    Date Modified: $Modtime: 2010-01-27 19:34:55+01:00 $ 

      Description: Interface voor trigger logic.

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  
end interface.
