{panaedra/msi/logic/ctop_interface.i}

interface panaedra.msdr.logic.i_triggerlogic:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/panaedra/msdr/logic/i_triggerlogic.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-08-07 21:22:38+02:00 $ 
    Date Modified: $Modtime: 2009-08-07 21:22:38+02:00 $ 

      Description: Interface voor trigger logic.

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  
end interface.
