{panaedra/msroot/msutil/logic/top_i/ctop_interface.i}

interface panaedra.msroot.msutil.interfaces.i_triggerlogic:  

  /****************************** Source Header ********************************\

      Description: Interface for trigger logic.

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  
end interface.
