using panaedra.msroot.msutil.logic.*.
using panaedra.msroot.msutil.interfaces.*.

{panaedra/msroot/msutil/logic/top_i/ctop_class.i} 

class panaedra.msroot.msutil.interfaces.sc_lang: 

  /****************************** Source Header ********************************\

      Description: Ovid class (Overload Identifier). Language definitions on msutil level.

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
  define public static property oDutch                      as i_language_dutch   no-undo get.
  define public static property oEnglish                    as i_language_english no-undo get.
  define public static property oAny                        as i_language_any     no-undo get.

end class.

/* EOF */ 
