{panaedra/msroot/msutil/logic/top_i/ctop_interface.i}

interface panaedra.msroot.msmonitor.interfaces.i_msmon_itempfilebuilder:  

    /******************************  Dvcs_ Header ********************************\
           Filename: $Archive:  $
            Version: $Revision:  $
         Programmer: $Author: $
       Date Checkin: $Date:  $
      Date Modified: $Modtime:  $

        Description: interface for tempfiles for use in msmon_feedback

    \*****************************  Include Files ********************************/

    /******************************* $NoKeywords:  $ *****************************/


  method public character CreateTempfile(
    hBufttMsMonFeedbackDefIP# as handle
    ).

end interface.

/* EOF */ 
