{panaedra/msroot/msutil/logic/top_i/ctop_interface.i}
interface paninui.view.init.display.i_bindingsourcetype_buffer:  

  /****************************** Source Header ********************************\

      Description: Empty interface

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/
  
end interface.

/* EOF */
