{panaedra/msi/logic/ctop_interface.i}
interface paninui.view.init.display.i_bindingsourcetype_buffer:  

  /******************************  Dvcs_ Header ********************************\
         Filename: $Archive: /ont/src/paninui/view/init/display/i_bindingsourcetype_buffer.cls $ 
          Version: $Revision: 1 $ 
       Programmer: $Author: $ 
     Date Checkin: $Date: 2009-09-02 16:45:02+02:00 $ 
    Date Modified: $Modtime: 2009-09-02 16:44:55+02:00 $ 

      Description: add_your_comments_here

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  
end interface.

/* EOF */
