{panaedra/msroot/msutil/logic/top_i/ctop_class.i}
using paninui.view.init.display.*.

class paninui.view.init.display.sc_bindingsourcetype: 

  /****************************** Source Header ********************************\

      Description: Helper class for overload ID interfaces for c_bindingsource. 

  \*****************************  Include Files ********************************/

  /******************************* $NoKeywords:  $ *****************************/

  define public static property i_Buffer as i_bindingsourcetype_buffer no-undo get.
  define public static property i_Query  as i_bindingsourcetype_query  no-undo get.

end class.

/* EOF */
